version: '3.3'

services:

  web:
    container_name: sakura-housing-beta-web
    build: .
    command: bash -c "./entry-point.sh"
    volumes:
      - .:/code
      - ./logs/debug.log:/webapp/logs/debug.log
    environment:
      ENVIRONMENT: 'beta'
    restart: always

  webserver:
    container_name: sakura-housing-beta-nginx
    build: ./nginx
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - 8081:80
    volumes:
      - ./nginx/snippets:/etc/nginx/snippets

  database:
    container_name: sakura-housing-development
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin
      POSTGRES_DB: sakura-housing
      ALLOW_IP_RANGE: 0.0.0.0/0
      DB_VENDOR: postgres
      DESTROY_DATABASE_ON_RESTART: 'False'
    ports:
      - 5435:5432
    volumes:
      - ~/.happy_app/data:/var/lib/postgresql/data
