# Generated by Django 3.1.1 on 2020-11-12 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='ToaNhas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.districts')),
            ],
            options={
                'db_table': 'toa_nhas',
            },
        ),
        migrations.CreateModel(
            name='KhachThues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cmt', models.CharField(blank=True, max_length=255, null=True)),
                ('cmt_NgayCap', models.DateField(blank=True, null=True)),
                ('cmt_NoiCap', models.CharField(blank=True, max_length=255, null=True)),
                ('cccd', models.CharField(blank=True, max_length=255, null=True)),
                ('cccd_NgayCap', models.DateField(blank=True, null=True)),
                ('cccd_NoiCap', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_NgayCap', models.DateField(blank=True, null=True)),
                ('passport_NgayHan', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('company_fax', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_tax_code', models.CharField(blank=True, max_length=255, null=True)),
                ('company_rep', models.CharField(blank=True, max_length=255, null=True)),
                ('company_rep_role', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('assistant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assistant_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('assistant_email', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khach_thues_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khach_thues_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'khach_thues',
            },
        ),
        migrations.CreateModel(
            name='ChuNhas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cmt', models.CharField(blank=True, max_length=255, null=True)),
                ('cmt_NgayCap', models.DateField(blank=True, null=True)),
                ('cmt_NoiCap', models.CharField(blank=True, max_length=255, null=True)),
                ('cccd', models.CharField(blank=True, max_length=255, null=True)),
                ('cccd_NgayCap', models.DateField(blank=True, null=True)),
                ('cccd_NoiCap', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_NgayCap', models.DateField(blank=True, null=True)),
                ('passport_NgayHan', models.DateField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('phone2', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('email2', models.CharField(blank=True, max_length=255, null=True)),
                ('so_TK', models.CharField(max_length=255)),
                ('chi_nhanh', models.CharField(max_length=255)),
                ('ngan_hang', models.CharField(max_length=255)),
                ('so_TK2', models.CharField(blank=True, max_length=255, null=True)),
                ('chi_nhanh2', models.CharField(blank=True, max_length=255, null=True)),
                ('ngan_hang2', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chu_nhas_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chu_nhas_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chu_nhas',
            },
        ),
        migrations.CreateModel(
            name='CanHos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('gcn', models.CharField(max_length=255)),
                ('gcn_NgayCap', models.DateField(max_length=255)),
                ('gcn_NoiCap', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=512)),
                ('note', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chu_nha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.chunhas')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='can_hos_created_by', to=settings.AUTH_USER_MODEL)),
                ('toa_nha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.toanhas')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='can_hos_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'can_hos',
            },
        ),
    ]
