# Generated by Django 3.1.1 on 2020-11-12 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(max_length=255)),
                ('can_ho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.canhos')),
            ],
            options={
                'db_table': 'contract_type',
            },
        ),
        migrations.CreateModel(
            name='DichVus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('don_vi', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('dinh_ky', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dich_vu',
            },
        ),
        migrations.CreateModel(
            name='HDGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_ho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.canhos')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hd_group_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hd_group_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hd_group',
            },
        ),
        migrations.CreateModel(
            name='HDThue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dk_gia_han', models.CharField(max_length=512)),
                ('gia_thue_per_month', models.IntegerField(blank=True, null=True)),
                ('gia_thue_per_month_nt', models.IntegerField(blank=True, null=True)),
                ('ky_tt', models.IntegerField()),
                ('tien_dat_coc', models.IntegerField()),
                ('tien_dat_coc_nt', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=512, null=True)),
                ('ngoai_te', models.CharField(max_length=10)),
                ('ty_gia', models.FloatField(blank=True, null=True)),
                ('ngay_lay_ti_gia', models.DateField(blank=True, null=True)),
                ('ngay_ki', models.DateField()),
                ('ngay_nhan', models.DateField()),
                ('ngay_tra', models.DateField()),
                ('hd_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.hdgroups')),
                ('khach_thue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.khachthues')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contracttype')),
            ],
            options={
                'db_table': 'hd_thue',
            },
        ),
        migrations.CreateModel(
            name='HDMoiGioi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tien_com', models.IntegerField()),
                ('chi_phi', models.IntegerField()),
                ('tien_chenh', models.IntegerField()),
                ('tien_tra_ky', models.IntegerField()),
                ('ky_tt', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=512, null=True)),
                ('hd_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.hdgroups')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.tenants')),
                ('type_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contracttype')),
            ],
            options={
                'db_table': 'hd_moi_gioi',
            },
        ),
        migrations.CreateModel(
            name='HDDichVu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tien_thuc_linh', models.IntegerField()),
                ('tien_dich_vu', models.IntegerField()),
                ('thoi_gian_thanh_toan', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=512, null=True)),
                ('hd_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.hdgroups')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.tenants')),
                ('type_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contracttype')),
            ],
            options={
                'db_table': 'hd_dich_vu',
            },
        ),
        migrations.CreateModel(
            name='HD2DichVus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('don_gia', models.IntegerField()),
                ('ky_tt', models.IntegerField()),
                ('dinh_muc', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=512, null=True)),
                ('dich_vu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.dichvus')),
                ('hd_thue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.hdthue')),
            ],
            options={
                'db_table': 'hd_2_dich_vu',
            },
        ),
    ]
