# Generated by Django 3.1.1 on 2020-11-15 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20201113_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hdmoigioi',
            old_name='chi_phi',
            new_name='tien_moi_gioi',
        ),
        migrations.RemoveField(
            model_name='hdmoigioi',
            name='ky_tt',
        ),
        migrations.RemoveField(
            model_name='hdmoigioi',
            name='tien_chenh',
        ),
        migrations.RemoveField(
            model_name='hdmoigioi',
            name='tien_com',
        ),
        migrations.RemoveField(
            model_name='hdmoigioi',
            name='tien_tra_ky',
        ),
    ]
