# Generated by Django 3.1.1 on 2020-11-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20201115_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hddichvu',
            name='type_contract',
            field=models.IntegerField(choices=[(1, 'HD Thue'), (2, 'HD Moi Gioi'), (3, 'HD Dich Vu')], default=3),
        ),
        migrations.AlterField(
            model_name='hdmoigioi',
            name='type_contract',
            field=models.IntegerField(choices=[(1, 'HD Thue'), (2, 'HD Moi Gioi'), (3, 'HD Dich Vu')], default=2),
        ),
        migrations.AlterField(
            model_name='hdthue',
            name='type_contract',
            field=models.IntegerField(choices=[(1, 'HD Thue'), (2, 'HD Moi Gioi'), (3, 'HD Dich Vu')], default=1),
        ),
        migrations.DeleteModel(
            name='ContractType',
        ),
    ]
