# Generated by Django 3.1.1 on 2020-11-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_auto_20201115_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdthue',
            name='ngay_ki',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hdthue',
            name='ngay_nhan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hdthue',
            name='ngay_tra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hdthue',
            name='tien_dat_coc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hdthue',
            name='tien_dat_coc_nt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
