# Generated by Django 3.1.1 on 2020-11-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20201115_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdthue',
            name='dk_gia_han',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
