# Generated by Django 3.1.1 on 2020-11-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_auto_20201115_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hddichvu',
            name='thoi_gian_thanh_toan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
