# Generated by Django 3.1.1 on 2020-11-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot_thanh_toan', models.CharField(max_length=512)),
                ('so_tien', models.IntegerField()),
                ('ngay_thanh_toan_du_kien', models.DateField()),
                ('ngay_thanh_toan_tt', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Paid'), (2, 'Unpaid'), (3, 'Error')], default=2)),
                ('note', models.CharField(blank=True, max_length=512, null=True)),
                ('hd_2_dichvu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.hd2dichvus')),
            ],
            options={
                'db_table': 'service_transaction',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('dot_thanh_toan', models.CharField(max_length=512)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Paid'), (2, 'Unpaid'), (3, 'Error')], default=2)),
                ('ngay_thanh_toan_du_kien', models.DateField()),
                ('ngay_thanh_toan_tt', models.DateField()),
                ('so_tien', models.IntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'payment_transaction',
            },
        ),
    ]
