# Generated by Django 3.1.1 on 2020-11-12 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Viewer'), (3, 'Disable')], default=2)),
                ('is_admin', models.BooleanField(default=False)),
                ('staff_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('phone2', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('email2', models.CharField(blank=True, max_length=255, null=True)),
                ('dkkd', models.CharField(max_length=255)),
                ('tax_code', models.CharField(max_length=255)),
                ('rep', models.CharField(max_length=255)),
                ('rep_role', models.CharField(max_length=512)),
                ('ten_tk', models.CharField(max_length=255)),
                ('so_TK', models.CharField(max_length=255)),
                ('chi_nhanh', models.CharField(max_length=255)),
                ('ngan_hang', models.CharField(max_length=255)),
                ('ten_tk2', models.CharField(blank=True, max_length=255, null=True)),
                ('so_TK2', models.CharField(blank=True, max_length=255, null=True)),
                ('chi_nhanh2', models.CharField(blank=True, max_length=255, null=True)),
                ('ngan_hang2', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.tenants'),
        ),
    ]
